// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./pages/about-me/index.vue')['default']
    App: typeof import('./App.vue')['default']
    Article: typeof import('./pages/article/index.vue')['default']
    Aside: typeof import('./pages/home/aside.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    Error: typeof import('./pages/error/index.vue')['default']
    Footer: typeof import('./layout/footer.vue')['default']
    Header: typeof import('./layout/header.vue')['default']
    Home: typeof import('./pages/home/index.vue')['default']
    Layout: typeof import('./layout/index.vue')['default']
    Main: typeof import('./pages/home/main.vue')['default']
    MdiAccountBoxMultiple: typeof import('~icons/mdi/account-box-multiple')['default']
    MdiArrowUpBold: typeof import('~icons/mdi/arrow-up-bold')['default']
    MdiFolderSearch: typeof import('~icons/mdi/folder-search')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiMessageText: typeof import('~icons/mdi/message-text')['default']
    MdiMicrosoftXboxControllerMenu: typeof import('~icons/mdi/microsoft-xbox-controller-menu')['default']
    MdiMoonFull: typeof import('~icons/mdi/moon-full')['default']
    MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    MdiMotionPlay: typeof import('~icons/mdi/motion-play')['default']
    MdiTimelineClock: typeof import('~icons/mdi/timeline-clock')['default']
    Menu: typeof import('./pages/menu/index.vue')['default']
    MessageBoard: typeof import('./pages/message-board/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./components/scrollToTop/index.vue')['default']
    SearchDialog: typeof import('./components/searchDialog/index.vue')['default']
    ThemeBtn: typeof import('./components/themeBtn/index.vue')['default']
    TimeLine: typeof import('./pages/time-line/index.vue')['default']
  }
}
